# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RemoteDataSync' do
    pod "AFNetworking", "~> 2.0"
end

target 'Sample' do
    pod "AFNetworking", "~> 2.0"
end

